apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-microservice
  template:
    metadata:
      labels:
        app: my-microservice
    spec:
      imagePullSecrets:
        - name: gar-secret
      containers:
        - name: ramya-app
          image: <+artifact.image>
          ports:
            - containerPort: 8080

